version: "3"
services:
    db:
        image: postgres:latest
        container_name: user-db-container
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=user-db
        volumes:
            - ./db-data:/var/lib/postgresql/data
        networks:
            - curioq-network

    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.1
        container_name: zookeeper-container
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - curioq-network

    kafka:
        image: confluentinc/cp-kafka:6.2.1
        container_name: kafka-container
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_DEFAULT_REPLICATION_FACTOR: 3
            KAFKA_NUM_PARTITIONS: 3
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_DELETE_TOPIC_ENABLE: "true"
        volumes:
            - ./kafka-data:/var/lib/kafka/data
        networks:
            - curioq-network

    auth-service:
        container_name: auth-service-container
        build:
            context: .
            dockerfile: auth-service/Dockerfile
        ports:
            - "8080:8080"
        networks:
            - curioq-network
        depends_on:
            - db
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db-container:5432/user-db
            - SPRING_DATASOURCE_USERNAME=admin
            - SPRING_DATASOURCE_PASSWORD=admin
            - SPRING_JPA_HIBERNATE_DDL_AUTO=none
            - dbhost=192.168.178.204
              
    security-lib:
        container_name: security-lib-container
        build:
            context: .
            dockerfile: security-lib/Dockerfile
        ports:
            - "9090:9090"
        networks:
            - curioq-network
        environment:
            - server.port=9090

networks:
    curioq-network: