version: "3"
services:
    db:
        image: postgres:latest
        container_name: user-db-container
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=admin
            - POSTGRES_DB=user-db
        volumes:
            - ./db-data:/var/lib/postgresql/data