name: CI-auth-service

on:
  push:
    branches:
      - main
    paths:
      - 'auth-service/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('auth-service/**/pom.xml') }}-${{ github.sha }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build auth-service
        run: mvn clean install -Dmaven.test.skip --file auth-service/pom.xml

      - run: mkdir auth-service/target && cp auth-service/target/auth-service-0.0.1-SNAPSHOT.jar auth-service/target
      - name: Publish JAR artifact
        uses: actions/upload-artifact@v2
        with:
          name: auth-service-jar
          path: auth-service/target/auth-service-0.0.1-SNAPSHOT.jar

  build-docker-image:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [build_and_test]

    steps:
      - uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Download JAR artifact
        uses: actions/download-artifact@v2
        with:
          name: auth-service-jar

      - name: Build Container image
        run: docker-compose build auth-service

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_REPO }}/auth-service:${{ github.sha }}
