name: CI-security-lib

on:
    push:
        branches:
            - main
        paths:
          - 'security-lib/**'

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build security-lib
        run: mvn clean install -Dmaven.test.skip --file security-lib/pom.xml
        
      - name: Stop and Remove Container
        run: docker-compose down

      - name: Build Docker Image
        run: docker-compose build

      - name: Deploy with Docker Compose
        uses: docker/compose-action@v2
        run: docker-compose up