name: CI

on:
    push:
        branches:
            - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - security-lib
          - auth-service
          - qa-service
          - user-service

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Cache the Maven packages to speed up build
        uses: actions/cache@v1
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ matrix.service }}-${{ hashFiles(format('{0}/pom.xml', matrix.service)) }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build ${{ matrix.service }}
        run: mvn clean install -Dmaven.test.skip --file ${{ matrix.service }}/pom.xml