name: CI

on:
    push:
        branches:
            - main

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Build Security Lib
        run: mvn clean install -Dmaven.test.skip --file security-lib/pom.xml

      - name: Build Authentication service
        run: mvn clean install -Dmaven.test.skip --file auth-service/pom.xml
        
      - name: Build QA service
        run: mvn clean install -Dmaven.test.skip --file qa-service/pom.xml
        
      - name: Build User service
        run: mvn clean install -Dmaven.test.skip --file user-service/pom.xml